version: '3'

services:
  test:
    container_name: test
    build:
      context: ../test
      dockerfile: Dockerfile.install
    image: test
    volumes:
      - ../test:/app
      - /app/node_modules
